### ISSUE TITLE
Getting a @mention for every 4 images I send to a channel

### ISSUE THREAD

**Issue by tabaha** [IanMitchell/aquarius#10]
[image](http://lies.deishuu.eu/KizuBot_2016-05-05_19-36-52.png)
The blank lines represent images sent

**Comment by IanMitchell** [comment]
HAHAH that's the same module, this is perfect

**Comment by tabaha** [comment]
Also, the same module isn't in a channel basis

**Comment by IanMitchell** [comment]
Yeah, I'll disable it for now. It was in testing

**Comment by IanMitchell** [comment]
Will be fixed in next update

**Comment by IanMitchell** [comment]
This should now be fixed
