### ISSUE TITLE
Make custom 8ball commands

### ISSUE THREAD

**Issue by zaneneuschuler** [IanMitchell/aquarius#100]
As I have a mass amount of meme responses for my personal 8ball that aren't exactly acceptable for everyone to use, having the ability to customize the 8ball responses would be helpful.

**Comment by IanMitchell** [comment]
Elmer would appreciate this as well; Will need...

- [ ] Database table of responses
- [ ] Method of adding replies
- [ ] Method of removing replies
- [ ] Method of clearing replies
- [ ] Method of listing replies
- [ ] Standard replies pre-populated when 8ball added to server

**Comment by IanMitchell** [comment]
Little too much work required for this; would rather put the time elsewhere.
