### ISSUE TITLE
Bet/Gamble Karma

### ISSUE THREAD

**Issue by eaglef2** [IanMitchell/aquarius#102]
Make it so 2 people can make a bet and possibly have a 3rd person witness the result of the gamble.

Something like this:
.bet \<amount_of_karma\> \<coinflip|@Witness\> \<@ChallengedGuy1\> \[@ChallengedGuy2...\] \[Message\]

Coinflip example:
Alice: .bet 5 coinflip @Bob
Aquarius:  Bet#25: Alice has bet that Bob loses a coinflip.
Bob: .accept 25
Aquarius: Result of Bet#25: @Bob wins 5 karma (at 47), @Alice loses 5 karma (at 23)

Witness example:
Alice: .bet 20 @Charlie @Bob Bernie wins the nomination
Aquarius: Bet#26: Alice has bet Bob that "Bernie wins the nomination" witnessed by Charlie
Bob: .accept 26
Charlie: .accept 26
... Bernie loses nomination
Charlie: .witness 26 @Bob wins
Aquarius: Result of Bet#26: @Bob wins 20 karma (at 67), @Alice loses 20 karma (at 3)

**Comment by IanMitchell** [comment]
Whoa, example usages. I like it 👍 

Will try to get to this when I can, bit of a break while I redesign my site.

**Comment by IanMitchell** [comment]
This would end up being a ton of work, so gonna pass on it.
