### ISSUE TITLE
Save battle.net profiles to database for overwatch command

### ISSUE THREAD

**Issue by PeriodBlood** [IanMitchell/aquarius#118]
Idea stems from Lapzbot, which has lot of functions built in for osu.
https://lapoozza.me/commands-list/

You can see one of the commands is 
`?setosu osu_user_name`

After setting your username, it saves it to the database under your discord user, so you can later type
`?osu [discord_user]`
and it will pull up your stats or someone else's stats in any other discord with Lapzbot, without typing your actual account in again.

**Comment by IanMitchell** [comment]
I like it!

**Comment by PeriodBlood** [comment]
Expanding this to the weather command, allow users to save a location that will automatically be used by default for that user by just typing .weather

**Comment by IanMitchell** [comment]
Up for grabs; I'll be doing other stuff

**Comment by IanMitchell** [comment]
v2 has a system for this
