### ISSUE TITLE
Advanced .reply specification with regexes

### ISSUE THREAD

**Issue by tobiaselder** [IanMitchell/aquarius#123]
Currently .reply only matches the requested string under some circumstances (complete match, start of line, idfk.)

Let's expand on this by letting the `.reply` add command interpret the first argument, the one it'll use to match for the reply trigger, as a regex if it begins and ends with `/`.

This offers a more powerful customization of reply behavior, while not making the feature harder to use in the current base case.

**Comment by IanMitchell** [comment]
This would take a lot of effort; I'm not sure if it would fit in the reply command or belong elsewhere either. Regardless, I'd rather put time elsewhere. Someone else can grab it if they really want this though
