### ISSUE TITLE
Add support for Celsius in the weather command

### ISSUE THREAD

**Issue by BluesYohan** [IanMitchell/aquarius#129]
I happen to live in Canada, and the weather command reports temperatures only in Fahrenheit. pls fix

**Comment by kevintongg** [comment]
Please implement this feature; you can do this as F/C!

`78F/25C`

**Comment by IanMitchell** [comment]
I think Dium has the right idea; as Ben suggested, a custom converter will work for this

**Comment by IanMitchell** [comment]
Added to the weather command, #119
