### ISSUE TITLE
Error: TypeError: Canot read property 'channel' of null

### ISSUE THREAD

**Issue by BluesYohan** [IanMitchell/aquarius#133]
So I tried to check the weather of my favourite country Djibouti (.w Djibouti) when I got that error. pls fix

**Comment by IanMitchell** [comment]
Searching for Kanji also results in some weird bugs

**Comment by IanMitchell** [comment]
When rate limited: 
```Error: FetchError: request to https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast where u='f' AND woeid in (select woeid from geo.places(1) where text="seattle")&format=json failed, reason: connect ECONNREFUSED <ip>```
