### ISSUE TITLE
Support a way to indicate term start and end for the choice feature

### ISSUE THREAD

**Issue by cheshyre** [IanMitchell/aquarius#134]
.c "something with spaces" "something else with spaces"
Expected result: "something with spaces" (full term)
Actual result: with (or "something)

I think this would be a quality of life improvement.

**Comment by IanMitchell** [comment]
Different from commas?

**Comment by cheshyre** [comment]
I didn't realize the syntax was commas, but either way this bug exists:
`me: .c "a, b", c
Aquarius: "a`

**Comment by IanMitchell** [comment]
This would be painful to do, so closing
