### ISSUE TITLE
Not all replies can be removed

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#156]
A reply with a `:P` trigger can't seem to be removed

**Comment by cheshyre** [comment]
I did some further testing and this behavior seems to be unique to the syntax `:StringContainingCapitals`. For example, `.reply remove` works for ":p" and ":aaaa", but not for ":P" or ":aAA" or ":AaA". This probably has something to do with the DB removal syntax. Another behavior worth mentioning is that after failing to delete the reply from the DB, the bot still thinks the reply was removed even though it still replies to it and lists it in `.replies`, making the only way to remove it overriding it with an entirely lower-case trigger and then removing that.

I recommend making the trigger lowercase before entering it into the DB, especially seeing as the actual .reply behavior is case insensitive.

Something else worth testing: similar strings but in the trigger reply instead might cause DB problems.

**Comment by IanMitchell** [comment]
My concern is that we'd have to change the reply syntax to be case insensitive, and I'm not sure I want to do that. I'm also not sure if the db entry is being removed correctly and the in-memory reply isn't, or if they both aren't being removed.

**Comment by CaleGlisson** [comment]
Do you mean the reply trigger word being case insensitive? If so that's already the case:

```
Cale - Today at 10:47 AM
keepo

AquariusBOT - Today at 10:47 AM
Keepo

Cale - Today at 10:47 AM
Keepo

AquariusBOT - Today at 10:47 AM
Keepo
```

**Comment by IanMitchell** [comment]
Apparently I don't know jack about my own bot ¯\_(ツ)_/¯

**Comment by IanMitchell** [comment]
Fixed by @cheshyre!
