### ISSUE TITLE
Help Syntax """Improvements"""

### ISSUE THREAD

**Issue by skiddiks** [IanMitchell/aquarius#171]
- For .help, include something that says "PM bot to manage all commands". Change "Available Commands" to "Enabled Commands" since I'm dumb and interpret "available" as all commands. 
- When you list commands in PMs, separate available and enabled commands
- Give an option to enable/disable multiple functions, i.e. .enable/disable choose, order
- If discuck doesn't allow bot PMs, possibly make management options for in-channel. For example, .help advanced would display the same thing as PMing the bot help
- On that note, also have in-channel enabling/disabling of features, i.e. .set choose on/off, .enable choose, w/e

**Comment by IanMitchell** [comment]
Yikes. This gets progressively harder haha

**Comment by IanMitchell** [comment]
v2 fixes this mostly
