### ISSUE TITLE
Update Weather Command

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#227]
I need to finish implementing and testing the Weather command

**Comment by IanMitchell** [comment]
@kevintongg you're pretty good at Discord embeds - any ideas on if they would work well for the Weather command?

**Comment by kevintongg** [comment]
@IanMitchell It would look a whole lot better than just enclosing the weather printout in a markdown block and I am sure there is a way to make it work.

**Comment by IanMitchell** [comment]
Decided to ship with the old-style weather command, and revisit making it more useful after launch

**Comment by IanMitchell** [comment]
Done!
