### ISSUE TITLE
Karma system update

### ISSUE THREAD

**Issue by elmerurbano** [IanMitchell/aquarius#25]
Add the following commands to karma

@bot karma @user - shows user's karma level
@bot karma shitlist - shows users with the lowest karma level

**Comment by elmerurbano** [comment]
Award/remove karma from multiple users in one command
@user @user ++/--

**Comment by IanMitchell** [comment]
Second one would break the cooldown, but definitely yes to the first two

**Comment by elmerurbano** [comment]
Allow for comments after karma command, just to describe what the karma is for
@user ++ [optional comment]

**Comment by IanMitchell** [comment]
Not to store, just for the trigger right?

**Comment by elmerurbano** [comment]
Not to store. It's for readability/ease of use.
So right now we have to do:
@Ian++
Funny joke dude

Instead, I want to be able to do:
@Ian ++ funny joke dude
