### ISSUE TITLE
Ignore responds with the wrong thing

### ISSUE THREAD

**Issue by CaleG** [IanMitchell/aquarius#344]
When using the form:

@Aquarius ignore add @user 

Aquarius responds with:
Added @Aquarius to my ignore list

**Comment by IanMitchell** [comment]
Turns out this is because discordjs/discord.js#2669 - they receive the API response and shove it into a data structure without modification, so the order isn't the order mentions appear in the message despite it being the intuitive way of handling this.

**Comment by IanMitchell** [comment]
We'll need to update:

* Karma
* Seen
* Ignore

To account for this

**Comment by IanMitchell** [comment]
Fixed in #336
