### ISSUE TITLE
Reply Usage Tracking

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#41]
It'd be cool to see what replies get used most often. A simple usage counter + an "active" flag that is toggled on removal would do it (that way we don't lose data on reply deletion)

**Comment by elmerurbano** [comment]
We need a reply command to see the available replies on the current server.

**Comment by IanMitchell** [comment]
New issue for that

**Comment by IanMitchell** [comment]
This isn't needed
