### ISSUE TITLE
Add Pokédex Command

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#49]
This is for you, @mechdriver.

Allow the user to pass in an id or name and grab information about the corresponding Pokémon

**Comment by IanMitchell** [comment]
Looks like the Poké API returns a ton of excess data, and isn't really what we need (also has some weird errors); looking at the Pokémon DB as an alternative.

**Comment by Mechdriver** [comment]
I mean, the extra data isn't garbage. We could use it in case we want to expand on the bot features. What sort of weird errors are you getting?

**Comment by IanMitchell** [comment]
It looks like the API is crashing - maybe on account of me hitting it with 722 requests on start 😨

**Comment by Mechdriver** [comment]
No rate limiting for a free app? Isn't that kind of weird?

**Comment by IanMitchell** [comment]
300 requests for a unique resource per day - so you can GET Charmander 300 times instead of limiting you to 300 pokemon. Unfortunately it looks like their server can't handle the load :(
