### ISSUE TITLE
Command Cooldown

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#71]
After X messages in Y minutes, the bot should throttle responses. If a user continues to spam the bot, they should be Aquarius muted

**Comment by CaleGlisson** [comment]
Possibly related to #56

**Comment by IanMitchell** [comment]
I think this would be a core feature instead of a command though... not sure how it'd work.

**Comment by IanMitchell** [comment]
#56 can be leveraged to mute users instead.
