### ISSUE TITLE
Dictionary command

### ISSUE THREAD

**Issue by CaleG** [IanMitchell/aquarius#72]
Syntax:
.dictionary word
!dictionary word
@bot dictionary word

Returns:
Definition of the word from some website

**Comment by Mechdriver** [comment]
Neat. Dibs.

**Comment by IanMitchell** [comment]
XML based :( http://dictionaryapi.com/

**Comment by CaleGlisson** [comment]
Doesn't work. Reopen 😉

**Comment by IanMitchell** [comment]
Forgot to add the API key. Works now
