### ISSUE TITLE
hashtags

### ISSUE THREAD

**Issue by skiddiks** [IanMitchell/aquarius#75]
support hashtags

**Comment by IanMitchell** [comment]
Can you elaborate on this one?

**Comment by skiddiks** [comment]
A hashtag is a type of label or metadata tag used on social network and microblogging services which makes it easier for users to find messages with a specific theme or content. Users create and use hashtags by placing the hash character (or pound sign) # in front of a word or unspaced phrase, either in the main text of a message or at the end.

**Comment by IanMitchell** [comment]
I hate you so much

**Comment by IanMitchell** [comment]
Implemented using emoji reactions
