### ISSUE TITLE
Anti-Zalgo Command

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#76]
Basically if a message contains Zalgos the bot auto-deletes the message

**Comment by Mechdriver** [comment]
Why? Also dibs for regex practice.

**Comment by IanMitchell** [comment]
Because I hate fun

**Comment by IanMitchell** [comment]
This looks promising: https://github.com/michaelrhodes/to-zalgo

**Comment by IanMitchell** [comment]
Part of v2
