### ISSUE TITLE
Can check episodes number above total episode count

### ISSUE THREAD

**Issue by LightArrowsEXE** [IanMitchell/aquarius#764]
**Describe the bug**
When performing a `.blame`, you can select a specific episode for it to check. When you pick a number above the total episode count, it returns a message saying the show has been finished.

![image](https://user-images.githubusercontent.com/42927908/108173845-f2a78100-70fe-11eb-8fe4-a724352924b9.png)

**To Reproduce**

1) `.blame #10000 random_show`
2) Bot returns message

**Comment by IanMitchell** [comment]
This should be fixed as well
