### ISSUE TITLE
pride icon

### ISSUE THREAD

**Issue by ryaain** [IanMitchell/aquarius#835]
We can set a pride icon for **JUNE**. Let's push for completion by 3/6 1:00 PM BST. We can address individual issues that arise as-needed.

**Comment by jacc** [comment]
man what

**Comment by IanMitchell** [comment]
ryaain you run a custom instance right? You shouldn't need anything here to change your avatar!

**Comment by ryaain** [comment]
the **PUBLIC** version should have a pride avatar

**Comment by joseywoermann** [comment]
> the **PUBLIC** version should have a pride avatar

@ryaain It is not possible to change the avatar or username of verified bots.

**Comment by advaith1** [comment]
you can change the avatar, just not the username

**Comment by ryaain** [comment]
Can we push for this to-be done? Is a **DEAD-LINE** extension needed? Advise as-needed.

**Comment by jacc** [comment]
yes ryaain, please give us an **EXTENSION** as needed.

**Comment by ryaain** [comment]
How much of an **EXTENSION* is needed?

**Comment by jacc** [comment]
At least until **July 1st, 1:00 PM BST**.

**Comment by ryaain** [comment]
Granted.

**Comment by ryaain** [comment]
Had a quick-second-thought. Pride month would be over by-then which would make this **SUGGESTION** useless-ed.

**Comment by jacc** [comment]
Valid concern - we should close this then.

**Comment by ryaain** [comment]
Do not troll **SIR**.

**Comment by jacc** [comment]
My apologies. Can we get a **DN extension**?

**Comment by ryaain** [comment]
what is **DN** **SIR**? advise me further.

**Comment by jacc** [comment]
![image](https://user-images.githubusercontent.com/6956351/120576072-2e393300-c3f0-11eb-882e-ebafff1d17e6.png)

**Comment by ryaain** [comment]
advise further as googleling this as come up with `deez nutz` which is not proper here. am I mistaken?

**Comment by MrCrypticXDev** [comment]
Are you on Discord?

**Comment by ryaain** [comment]
yes sir. you should be the last one to complain about my grammer because you just stolled the **topgg** logo xD

**Comment by MrCrypticXDev** [comment]
And they are fine with it...

**Comment by ryaain** [comment]
warning 1 for offtopicness in github issue

**Comment by jacc** [comment]
what happens at warning 2

**Comment by ryaain** [comment]
stop trolling **SIR**

**Comment by MrCrypticXDev** [comment]
@ryaain You opened a Github issue no one would of open titled "pride icon" & you been pretty off-topic for the record.

**Comment by ryaain** [comment]
ok mr know-it-all xD

**Comment by IanMitchell** [comment]
This has gotten pretty off-topic, so I'm gonna close the issue
