### ISSUE TITLE
Karma rebalance overhaul alternative

### ISSUE THREAD

**Issue by tobiaselder** [IanMitchell/aquarius#93]
> Kyle - Today at 1:24 PM
> Easy way to fix the value is have it subtract from yourself to give to others
> No magic karma
> Toby - Today at 1:25 PM
> ACTUALLY
> SOLID IDEA
> do you think zero-sum, or everyone gets +1 every day
> Kyle - Today at 1:26 PM
> No free karma
> Give a karma pay a karma
> Like capitalism intended
> Toby - Today at 1:27 PM
> however, in capitalism, there is the ability to extract raw capital
> i.e. mining or whatever
> so value has to come from somewhere
> Kyle - Today at 1:27 PM
> Bot controls the raw capital
> Toby - Today at 1:27 PM
> but how is it distributed
> Kyle - Today at 1:27 PM
> Say if you get like 5 karma from 5 different people in an hour bot refunds them and you keep the 5
> Toby - Today at 1:27 PM
> 👌
> @ Ian pls
> Kyle - Today at 1:28 PM
> It'll keep the comment quality high
> Bot could also monitor votes to remove karma for the karma minus
> NEW MESSAGES
> Kyle - Today at 1:28 PM
> Ding
> AquariusBOT - Today at 1:28 PM
> ching
> Kyle - Today at 1:29 PM
> Stupid bot
> Ian - Today at 1:29 PM
> Kyle, open an issue
> https://github.com/IanMitchell/aquarius/issues
> GitHub
> IanMitchell/aquarius
> aquarius - A discord bot
> 
> or @ Toby
> Kyle - Today at 1:30 PM
> if only I could
> I won't touch your filthy code shit
> if only I could
> Ian - Today at 1:32 PM
> you don't have to code
> just open an issue saying "here's how I think karma should work"
> and then I get to it when I can(edited)
> Kyle - Today at 1:33 PM
> @ Toby fix it for me pls

**Comment by IanMitchell** [comment]
I won't be pursuing this

**Comment by tobiaselder** [comment]
F
