### ISSUE TITLE
Disable Seen tracking unless added

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/aquarius#95]
It currently tracks all users

**Comment by Mechdriver** [comment]
Why is this necessary to disable?

**Comment by IanMitchell** [comment]
If a server doesn't want the seen command tracking all their users seems a little excessive and unnecessary - it also feels a bit like an invasion of privacy

**Comment by IanMitchell** [comment]
Think I'll leave this up - there's some complaints about not being able to add it and .seen someone right away.
